---
#1. Cette tache permet d'installer Apache (httpd) a l'aide du module apt
- name: "apache installation"
  apt:
    name: "apache2"
    state: "present"

#2. Cette tache active le service Apache
- name: "apache service activation"
  service:
    name: "apache2"
    state: "started"
    enabled: yes

#3. Cette tache fait appel a un autre fichier de configuration pour installer PHP. Elle est executable uniquement si la variable php_install est vraie (par defaut, elle est fausse)
- name: "install php packages"
  include: "php-install.yml"
  when: php_install|default(False)|bool
