---
#1. Install Apache module
- name: "apache installation"
  apt:
    name: "apache2"
    state: "present"

#2. Enable apache service
- name: "apache service activation"
  service:
    name: "apache2"
    state: "started"
    enabled: yes

#3. Call php-install.yml if php not install yet
- name: "install php packages"
  include: "php-install.yml"
  when: php_install|default(False)|bool
