---
#1. Cette tache installe PHP et ses extensions
- name: "install php packages"
  apt:
    name: "php, php-mysql, php-xml, php-mbstring, php-intl" 
    state: latest
  changed_when: yes
  notify: ["apache restart"]

