---
#Database
mediawiki_db_name: "mediawiki"

#User & Password
mediawiki_db_user: "mediawiki"
mediawiki_db_password: "AnsibleOC!"
mediawiki_admin_user: "admin"
mediawiki_admin_password: "AnsibleOC!"

#Mediawiki name and title
mediawiki_name: "mediawiki" 
mediawiki_title: "Mon super Mediawiki!"

#Installation directory
mediawiki_directory: "/var/www/html/{{mediawiki_name}}"

#Maintenance directory
mediawiki_maintenance_directory: "{{mediawiki_directory}}/maintenance"

#Define first mariadb groups node
mediawiki_db_host: "{{groups.db.0}}"

#URL of mediawiki sources
mediawiki_archive_url: "https://releases.wikimedia.org/mediawiki/1.39/mediawiki-1.39.3.tar.gz"
